### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by yanuas123** [abraia/abraia-nodejs#1]
![image](https://user-images.githubusercontent.com/36739828/55673535-d9520e80-58b1-11e9-989c-26b4f71b403f.png)

const abraia = require('gulp-abraia');
exports.ABRAIA_KEY = "NWE1YTM1ZmEyMmMwMDAwMDpUTDJGdmhMNlRGRWdnSnd0aWh3Z0dVdjFtQ1R3ZG9iQg==";

function minify_image() {
	return src(routes.minify_image.src)
		.pipe(abraia())
		.pipe(dest(routes.minify_image.dest));
}

**Comment by jrrodri** [comment]
You need to define the environment variable ABRAIA_KEY. You can do it in the gulpfile.js changing your code as bellow. The process.env.ABRAIA_KEY must be the first line of your file.

process.env.ABRAIA_KEY = 'NWE1YTM1ZmEyMmMwMDAwMDpUTDJGdmhMNlRGRWdnSnd0aWh3Z0dVdjFtQ1R3ZG9iQg==";

const abraia = require('gulp-abraia');

function minify_image() {
return src(routes.minify_image.src)
.pipe(abraia())
.pipe(dest(routes.minify_image.dest));
}

**Comment by yanuas123** [comment]
It works. Thank you!
But please, add this part to your npm tutorial, because it leads to confusion.
