### ISSUE TITLE
Not work ABRAIA_KEY

### ISSUE THREAD

**Issue by yanuas123** [abraia/abraia-nodejs#2]
Get your free API key and define the ABRAIA_KEY environment variable.
code: export ABRAIA_KEY=your_api_key

This code from your tutorial. It not working.

**Comment by jrrodri** [comment]
If you are on Windows, you need to define the ABRAIA_KEY running the next command in your console:

set ABRAIA_KEY=your_api_key

You can also define this value in your node file, before importing the abraia library, as bellow:

process.env.ABRAIA_KEY = 'your_api_key'

const abraia = require('abraia/abraia')

**Comment by yanuas123** [comment]
It works. Thank you!
But please, add this part to your npm tutorial, because it leads to confusion.

**Comment by jrrodri** [comment]
Sure. Thank you!

For any doubt or question send us an email to:   support@abraiasoftware.com
